[project]
name = "emind"
dynamic = ["version", "description", "readme", "authors", "classifiers", "dependencies", "optional-dependencies", "scripts"]
requires-python = ">=3.10"

[build-system]
requires = ["setuptools>=68.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["Emind*", "training*", "data_pipeline*", "eval*", "zhengliu*"]

[tool.ruff]
line-length = 120
target-version = "py310"

[tool.ruff.lint]
ignore = ["E501", "F403", "F405"]

[tool.ruff.format]
quote-style = "double"

[tool.isort]
profile = "black"
line_length = 120
